### ISSUE TITLE
Feature request: move "Man: Open page" lower in context menu

### ISSUE THREAD

**Issue by geertj** [meronz/vscode.manpages#14]
Nice little extension!

I use right-click on an identifier -> open definition extensively when browsing code, and it would be nice if that command continued to be the top command in context menu, as I use it much more often than opening a manpage. Could the "Man: open page" action be put somewhat lower in the menu? Alternatively could it be made configurable?

**Comment by GitMensch** [comment]
I vote for that :-)

**Comment by ldelossa** [comment]
This is a good one. 

Right now I actually use https://marketplace.visualstudio.com/items?itemName=constanze.mp-lookup since it has a command 'lookupFromSelection' which I can then emulate the vim keyboard shortcut `shift-k` to perform a man page lookup for the word highlighted. 

This would be really nice to see in this extension, since I do prefer this one a bit more, its just I need a way to emulate vim's super quick man-page lookup. 

The command could of course be tied to a context menu item so we can have both :)

**Comment by meronz** [comment]
Release 0.1.5 should address both concerns. I'm closing this issue, feel free to open a new one if the features implemented are not enough :)

Related PR: https://github.com/meronz/vscode.manpages/pull/31

**Comment by GitMensch** [comment]
Sounds nice, thank you. Please push a tag/release to GH, too :-)

**Comment by ldelossa** [comment]
Thank you!!
